version: '3.4'

services:
  typesense:
    image: typesense/typesense:0.24.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=test --enable-cors'
    healthcheck:
      test: curl --fail http://localhost:8108/health" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  app:
      build: .
      ports:
        - "8011:8011"
      depends_on:
        - typesense
      environment:
        - FLASK_ENV=development  
